### ISSUE TITLE
Guide for setting up a code quality checker

### ISSUE THREAD

**Issue by cmutel** [BONSAMURAIS/python-skeleton#5]

**Comment by cmutel** [comment]
Sonar cloud was suggested, and is in the README; looks a bit complicated to get the tokens set up.

**Comment by tngTUDOR** [comment]
I suggest we consider using : 
* a _local_ docker based sonar server and execute an analysis prior to commit && push 
* create a sonarcloud.io for the "public" facing part of the code. The analysis should be run automagically with the help of CI

**Comment by cmutel** [comment]
That sounds great, but means that you are volunteering to write the instructions on how to set that up :)

**Comment by tngTUDOR** [comment]
Yes I do ;)

**Comment by tngTUDOR** [comment]
Here is a quick and dirty howto for the code quality check à la SONAR:
https://github.com/tngTUDOR/pycodeq

**Comment by cmutel** [comment]
Added some basics in 3e66cd08bdd043ad8704f0ee8ad16d8405783b19
