### ISSUE TITLE
Coding standards and methods: Hackathon intro tutorial

### ISSUE THREAD

**Issue by cmutel** [BONSAMURAIS/python-skeleton#7]
One of the first things we will do at the hackathon is discuss coding standards and methods. Not everyone will be using Python, but most will, so going into the skeleton makes sense. It would also be nice to give a brief introduction to tests, including TDD.

Should also consider making general recommendations on libraries, e.g. what to do with datetimes (stdlib, [arrow](https://arrow.readthedocs.io/en/latest/), pandas, numpy, etc.); [appdirs](https://github.com/ActiveState/appdirs) for local file storage; when to use pandas; and (given that we won't have a web app skeleton) how to set up a simple web app using flask (?). Not more than a few minutes here, just to help people from having to research stuff on their own.

@tngTUDOR You are assigned this task 🤕 !

**Comment by tngTUDOR** [comment]
ack

**Comment by cmutel** [comment]
@tngTUDOR Please upload your slides to the hackathong repo and add a link to the `README`, then close this (when you have time).

**Comment by cmutel** [comment]
Good enough for now :)
