### ISSUE TITLE
Py Skeleton: First complete draft

### ISSUE THREAD

**Issue by cmutel** [BONSAMURAIS/python-skeleton#8]
- [x] Code and guide for automatic deployment to anaconda.org
- [x] Trial run by outside participant(s)

**Comment by tngTUDOR** [comment]
If all projects will be under the BONSAMURAIS organization, then pushing python packages to anaconda.org/conda-forge would require the organization to generate tokens and so on, right ?

**Comment by tngTUDOR** [comment]
https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/use-conda-with-travis-ci.html?highlight=travis

**Comment by cmutel** [comment]
1) Sorry, conda-forge is something different. For now it would be posted to people's personal conda.org accounts.

2) Unless we want to set up a bonsai conda channel. At some point we should have discuss how we manage IT competencies.

3) Uploading to conda.org is really easy, you just generate a token from your conda account, and then add this as a secret to the travis configuration. It is one minute (when you do it the second time :)

**Comment by cmutel** [comment]
Also, I personally don't think that most projects will be under BONSAMURAIS in the medium term. We want to be inclusive, not exclusive, and celebrate the contributions of each of our contributors.

**Comment by cmutel** [comment]
Trial run done with @jakobsarthur - closing issue.
