### ISSUE TITLE
Using markdown for code: Guide or switch recommendation to MkDocs

### ISSUE THREAD

**Issue by cmutel** [BONSAMURAIS/python-skeleton#9]
# Pros

We are asking people to learn markdown for all Github-related stuff, no real reason to learn ReST as well.

# Cons

* Markdown is [inconsistent and lacks roles](https://www.ericholscher.com/blog/2016/mar/15/dont-use-markdown-for-technical-docs/).
* Getting docstrings from code is very nice (possible in MkDocs only through a plugin)

@tngTUDOR Any opinion on this? 

Of course, this is only a recommendation, people can still choose what fits them best.

**Comment by tngTUDOR** [comment]
I think Markdown is enough.
